### PR TITLE
Energy Ship (3D)

### PR DESCRIPTION
**Pull request by yandonman**
Author
Landon Manning yandonman@hotmail.com

License
Content released under GPL 2.0 and Creative Commons
Attribution-ShareAlike 3.0.

The assets

lightning_harsch.jpg
negx.png
negy.png
negz.png
pos.x.png
posy.png
posz.png
ship-design-contained-energy-scout.obj
are licensed under the terms of the Creative Commons
Attribution-ShareAlike 3.0 Unported License.

http://creativecommons.org/licenses/by-sa/3.0/.

Editor

Clara.IO

### CODE REVIEW

**Comment by adrianbroher** [comment]
~~Model is no used in project, so I'm closing this PR.~~

~~Also we never found out properly export the model from Clara.IO.~~

It seems like it is already used.  Well, now how to import it into a readable format?

**Comment by Vezzra** [comment]
I have no idea. You can actually import the model into Blender, but apparently the materials and textures don't get imported correctly. The model is there, and looks correct AFAICT, but the materials all got reset to default values, so it's grey in grey.

One of our graphics folks (@V-ktor? @banduri? And who else has been around lately) could try to recreate the texturing if so inclined. I haven't heard or seen anything from @yandonman for a long time...

**Comment by V-ktor** [comment]
This is because the mtl files are missing.

**Comment by Vezzra** [comment]
Which basically means the materials need to be recreated from scratch, right? Any idea how difficult that might be, or worth the effort...?

**Pull request closed without merging**
